[theme]
base = "light"
primaryColor = "#087f8c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#18364a"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
